### ISSUE TITLE
コードの気になるところ

### ISSUE THREAD

**Issue by kosakasakas** [iwanao731/MotionGraph#1]
ロジックとか見てないので、書き方とかで気になる点だけ指摘します.
## ofApp

https://github.com/iwanao731/MotionGraph/blob/master/src/ofApp.cpp#L21
loadMotionってMotionが持っててもいいんじゃないの？

```
motion.load(path)
```

みたいな. 作りの問題だから別にいいけど.

https://github.com/iwanao731/MotionGraph/blob/master/src/ofApp.cpp#L22
まずmotion_graphはメンバ変数なのでそれがわかるような記述にしてある方がいいと思うよ.

```
_motion_graph
m_motion_graph
```

この辺はプロジェクトとか人によるのでなんでもいいけど、なんかしら規則があると普通の変数と違いがわかっていい.

あと、変数の書き方でスネークケースとキャメルケースが混在してるのでそれも統一した方が見易い.

```
## スネークケース
motion_graph
## キャメルケース
motionGraph
```

https://github.com/iwanao731/MotionGraph/blob/master/src/ofApp.cpp#L43
これはmgPlayer.draw();より先に描画されるけどいいの？
何が描かれるかわからんけど上書きされるよ

https://github.com/iwanao731/MotionGraph/blob/master/src/ofApp.cpp#L61
ofGetWidth()-200, ofGetHeight()-40って計算もったいないから固定でよくない？windowって可変だっけ？どうでもいいけど

https://github.com/iwanao731/MotionGraph/blob/master/src/ofApp.cpp#L154
コピーが発生するのでコンスト参照で渡しましょう.

```
const string& filename
```

splitもそうだけど、グローバルに関数勝手においていいのかな？多分同じ名前があると衝突すると思う.

```
namespace {
    void loadMotion(const string& filename, Motion &motion)
    {  ...  }
}
```

みたいな感じで無名名前空間でくくるとこのファイル内のみで有効になるのでいいよ.
もしくはstatic関数にするか.

https://github.com/iwanao731/MotionGraph/blob/master/src/ofApp.cpp#L173
結構スタンダードな機能っぽい関数なんだけど、標準ライブラリでないのこれ？
もしくはofDirとかにありそう.
ないなら仕方ないけどあったらもったいない.

一旦ofAppだけ見ました.

**Comment by kosakasakas** [comment]
## Motion

https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.h#L17
Motionというかなり普遍的な名称をクラス名に用いているので、いろいろ衝突の危険性がある.
名前に独自の接頭語をつける（例えばofのクラスは全部ofってついてるよね？そんな感じ）か、名前空間を切るかした方がいい.

```
## 名前空間を切る場合
namespace Euclid {
    class Motion
    {...};
}

## classを使う側
using namespace Euclid;
Motion m;
## もしくは
Euclid::Motion m;
```

https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.h#L9
上記に関連して、インクルードガードも強化するべき

```
#ifndef ____Euclid__Motion____
```

とか. じゃないと衝突した時にこのクラスは読み込みすらされなくなる.

https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.h#L25
https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.h#L27
参照で返した方がコピーが発生しなくていい. あとconstつけた方がコンパイラ最適化がかかって早くなる.

```
std::string& getLabel() const { return this->mLabel; }
```

さらに言うと、このgetしたstringの値が変更されないのであれば、戻り値もconstにした方がいい.

```
const std::string& getLabel() const { return this->mLabel; }
```

https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.h#L28
今までの流れを考えると、これもコピーしないように参照で返すのが良さそう.
だけど、これはメンバ変数を返しているわけではないので、もしかしたら生成して渡しているのかもしれない.
なので、コピー渡しをしなきゃいけない仕様なのかもしれない.
と思って、先に実装を見てみる.
https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.cpp#L24
メンバ渡してるやんけ.
ということでこれも参照でok。

https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.h#L30
この引数のstd::vector<Pose> posesとかすげー巨大になりそうな予感がするんだけど.
絶対参照で渡すべき.

```
void setPoses(std::vector<Pose>& poses, int nFrames);
```

もしかしたらconstで渡せる方がいいかもしれない.
と思って実装を見てみる.https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.cpp#L29
メンバーにコピーしているだけだった。なのでconstつきでok.
(そしてなぜかint nFramesの方にはconstが付いている... ポインタじゃないと結局コピーするからあんまり意味ないよ)

```
void setPoses(const std::vector<Pose>& poses, int nFrames);
```

そして余談ですが、もし仮にこのposeが使い切りで、setPoseしたら所有権を全てMotionに移してしまって良いのであれば、C++11以降のstd::moveが使えます.
https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.cpp#L29
の実装は

```
this->mPoses = std::move(poses);
```

にできる可能性がある.

https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.h#L40
メンバ変数に接頭語であるmが付いてる. これはいいこと

https://github.com/iwanao731/MotionGraph/blob/master/src/Motion.h#L44
これはここだけ見ても一概に言えないところなんだけど、個人的には参照で持ちたい.

```
std::vector<Pose&> mPoses;
```

だけど、もしPoseがMotionしかもっていないのであれば、参照にしてはいけない.
これは設計がどうなっているかによる.
他に絶対にPoseを所持している人がいるなら参照でもいい.

Motionのレビューは以上です.

全体として、知っておいた方がいいのは、ゲッタとセッタの書き方.
メンバ変数として、Hoge m_hogeがあるとすると、

```
## ゲッタ const
const Hoge& getHoge() const
{
    return m_hoge;
}
## ゲッタ 非const
Hoge& getHoge() const
{
    return m_hoge;
}
## セッタ
void  setHoge(const Hoge& hoge)
{
    m_hoge = hoge;
}
```

って感じで実装した方がいい.
この点についてもう他のところは指摘しないので、適宜いい感じに直してください.

**Comment by iwanao731** [comment]
# ofApp

https://github.com/iwanao731/MotionGraph/blob/master/src/ofApp.cpp#L21  
Motionクラスに持たせることも考えたんだけど，その場合にbvhの読み込みをofxBvh等の他のaddonで行うことになると思って，クラスの依存度が高くなると思ったので，Motionに変換してからMotionクラスに渡してる．そのかわりに，BVHConverterっていうのを作ってそれで変換してMotionに渡すという手間なことをしてるのだけど，そこはどう思う？

**Comment by iwanao731** [comment]
# Motion
-  細かいんだけど，以下は好みの問題？

```
string& filename;
string &filename;
```
- 以下のようにしたらすごい数のSemantic Issueが出たのでやめました->なぜ？
  `std::vector<Pose&> mPoses;`
- `function(const int& index)`
  みたいにintまで参照にすべき？
- 関数の後につけるconstってどういう意味がある？ 
  std::string& getLabel() const { return this->mLabel; }

**Comment by kosakasakas** [comment]
> 細かいんだけど，以下は好みの問題？

好みの問題だと思う.あんまり気にしたことなかった.

> 以下のようにしたらすごい数のSemantic Issueが出たのでやめました->なぜ？

```
void setPoses(const std::vector<Pose&>& poses, int nFrames);
```

これも変えた？
あと、参照先の実態がなくなってる場合はエラーが出ると思う.

> みたいにintまで参照にすべき？

これはすべきではない.
intは4バイトでポインタも32bitマシンなら4バイトなので別にintのコピーとポインタのコピーは変わらないので普通やらない.
さらに、const_cast<int*>(&index)とかされて中身が書き換えられる可能性もあるので普通にコピーでいい気がする. そんなことしないけど.

> 関数の後につけるconstってどういう意味がある？ 

constついてると関数内でメンバ変数の書き込みができなくなるのでバグを防ぐことができる.
あとコンパイラの最適化に役立つと思われる.

**Comment by kosakasakas** [comment]
> Motionクラスに持たせることも考えたんだけど，その場合にbvhの読み込みをofxBvh等の他のaddonで行うことになると思って，クラスの依存度が高くなると思ったので，Motionに変換してからMotionクラスに渡してる．そのかわりに，BVHConverterっていうのを作ってそれで変換してMotionに渡すという手間なことをしてるのだけど，そこはどう思う？

ラッパーを噛ませること自体は全然いいと思う.
ただ、実装を見ると、関数内で作った変数を、
https://github.com/iwanao731/MotionGraph/blob/master/src/BVHConverter.cpp#L13
コピーして返してるじゃん、
https://github.com/iwanao731/MotionGraph/blob/master/src/BVHConverter.cpp#L34
これ遅くないすかね？
フレーム数分の頂点データとか持ってるんだよね多分？すげーコピー発生するんじゃね？

おとなしく参照で渡すのがいいと思われる.

```
void BVHConverter::ToMotion( Euclid::Motion& motion, const mlib::ofxDigitalDanceBvh &bvh)
{
    .....
}
```

**Comment by xiaoiker** [comment]
There  is no mlib::ofxDigitalDanceBvh in openframeworks , where does this come from?

**Comment by iwanao731** [comment]
Hi! You can download from here.
https://github.com/DigitalDanceGroup/ofxDigitalDance
